# Generated by Django 3.0.2 on 2020-01-07 18:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='RowModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2500), django.core.validators.MinValueValidator(1900)], verbose_name='year')),
                ('week', models.PositiveIntegerField(verbose_name='week number')),
                ('day_1', models.DurationField(blank=True, null=True, verbose_name='monday')),
                ('day_2', models.DurationField(blank=True, null=True, verbose_name='tuesday')),
                ('day_3', models.DurationField(blank=True, null=True, verbose_name='wednesday')),
                ('day_4', models.DurationField(blank=True, null=True, verbose_name='thursday')),
                ('day_5', models.DurationField(blank=True, null=True, verbose_name='friday')),
                ('day_6', models.DurationField(blank=True, null=True, verbose_name='saturday')),
                ('day_7', models.DurationField(blank=True, null=True, verbose_name='sunday')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ProjectModel', verbose_name='project')),
            ],
            options={
                'verbose_name': 'row',
                'verbose_name_plural': 'rows',
                'ordering': ('-id',),
                'unique_together': {('year', 'week', 'project')},
            },
        ),
    ]
